#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

# colors
source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
sketchybar --bar \
  position=top \
  height=30 \
  blur_radius=30 \
  color=$BAR_COLOR

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:14.0"
  label.font="SF Pro:15.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"
############################

#### Adding Left Items ##########
# aerospace -> left
source "$ITEMS_DIR/aerospace.sh"

# current app -> left
source "$ITEMS_DIR/front_app.sh"
#################################

##### Adding Right Items #####
# clock -> right
source "$ITEMS_DIR/calendar.sh"

# volume -> right
source "$ITEMS_DIR/volume.sh"

# battery -> right
source "$ITEMS_DIR/battery.sh"
#################################

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
